# ------------------------------------------------------------------------------------
# Module: empty_algorithm_template.py
# Summary: template algorithm class, factory and optional GUI registry definition.
# Implementation: the module exposes a minimal custom algorithm skeleton with clear
# extension points for initialization, offspring generation, survivor selection and
# generation-level adaptation.
# Responsibility: serves as the starting point for implementing a new research
# algorithm that remains compatible with the GUI and the pymoo-style execution flow.
# ------------------------------------------------------------------------------------

from __future__ import annotations

from typing import Any, Dict

import numpy as np

from .research_common import PopulationState, ResearchMOOAlgorithm, parse_probability


class EmptyAlgorithmTemplate(ResearchMOOAlgorithm):
    # Minimal template for a custom multiobjective algorithm built on top of the
    # shared pymoo-compatible research base class.

    implementation_source = "template for user implementation"

    def __init__(
        self,
        population_size: int = 100,
        archive_size: int = 100,
        crossover_rate: float = 0.9,
        mutation_rate: float = 0.1,
        template_bias: float = 0.5,
        seed: int = 1,
    ) -> None:
        # Store the basic configuration of the template algorithm.
        # Args:
        # population_size (int): Number of individuals kept in each generation.
        # archive_size (int): Size of the helper archive used by the base class.
        # crossover_rate (float): Probability of crossover.
        # mutation_rate (float): Probability of mutation.
        # template_bias (float): Example custom parameter reserved for custom logic.
        # seed (int): Random seed used for reproducible runs.
        super().__init__(
            population_size=population_size,
            archive_size=archive_size,
            crossover_rate=crossover_rate,
            mutation_rate=mutation_rate,
            seed=seed,
        )
        self.template_bias = parse_probability(template_bias, "template_bias")

    def after_initialize(self) -> None:
        # Optional hook executed after the initial population has been created.
        # Add custom memory, model warm-up or statistics initialization here.
        return None

    def guided_candidates(self) -> np.ndarray:
        # Optional hook for extra candidate solutions generated by custom logic.
        # Returns:
        # np.ndarray: Extra decision vectors to be merged with the standard offspring.
        # Return additional solutions if the algorithm uses prediction, memory or repair.
        return np.empty((0, self.n_var), dtype=float)

    def create_offspring(self) -> np.ndarray:
        # Build offspring for one generation.
        # The default pipeline below is safe and fully compatible with the base class.
        # Replace or extend it when implementing your own variation operators.
        parent_pairs = self.select()
        offspring = self.crossover(parent_pairs)
        offspring = self.mutation(offspring)

        # Example extension point for custom variation logic.
        # offspring = your_custom_operator(offspring)
        return offspring

    def environmental_selection(
        self,
        X: np.ndarray,
        F: np.ndarray,
        CV: np.ndarray,
        n_survive: int,
    ) -> PopulationState:
        # Select survivors that move to the next generation.
        # Args:
        # X (np.ndarray): Decision vectors of candidate solutions.
        # F (np.ndarray): Objective values of candidate solutions.
        # CV (np.ndarray): Constraint violations of candidate solutions.
        # n_survive (int): Number of survivors to keep.
        # Returns:
        # PopulationState: Selected population snapshot.
        # Start from the default NSGA-II-like feasible-first selection.
        # Replace this block if your algorithm uses custom ranking, density,
        # decomposition or archive-based survival.
        return super().environmental_selection(X, F, CV, n_survive)

    def after_generation(self, previous: PopulationState, current: PopulationState) -> None:
        # Optional hook executed after each completed generation.
        # Args:
        # previous (PopulationState): Population before the update.
        # current (PopulationState): Population after the update.
        # Update custom adaptation rules, statistics, local models or memories here.
        _ = previous, current
        return None


def make_empty_algorithm_template(
    population_size: int = 100,
    archive_size: int = 100,
    crossover_rate: float = 0.9,
    mutation_rate: float = 0.1,
    template_bias: float = 0.5,
    seed: int = 1,
) -> EmptyAlgorithmTemplate:
    # Factory creating a ready-to-edit template algorithm instance.
    return EmptyAlgorithmTemplate(
        population_size=population_size,
        archive_size=archive_size,
        crossover_rate=crossover_rate,
        mutation_rate=mutation_rate,
        template_bias=template_bias,
        seed=seed,
    )


EMPTY_ALGORITHM_TEMPLATE_DEFINITION: Dict[str, Any] = {
    "label": "Empty Algorithm Template",
    "factory": make_empty_algorithm_template,
    "form_fields": {
        "population_size": {"default": 100, "kind": "int", "minimum": 1},
        "archive_size": {"default": 100, "kind": "int", "minimum": 1},
        "crossover_rate": {"default": 0.9, "kind": "float", "minimum": 0.0, "maximum": 1.0},
        "mutation_rate": {"default": 0.1, "kind": "float", "minimum": 0.0, "maximum": 1.0},
        "template_bias": {"default": 0.5, "kind": "float", "minimum": 0.0, "maximum": 1.0},
        "seed": {"default": 1, "kind": "int", "minimum": 0},
    },
    "form_note": (
        "Template for implementing a new pymoo-compatible algorithm. "
        "Register this definition in algorithms/__init__.py only after filling in the custom logic."
    ),
}
